### ISSUE TITLE
Implement custom buttom mapping check/save/load

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#12]
ttd

**Comment by calexil** [comment]
this one is gonna be a doozy @benmoran56 

I have done a ton of cleanup

please rebase your fork, also note to backup your deadzone slider somewhere I removed it since global items are a no no

**Comment by benmoran56** [comment]
This should be easier to do, now that the program is refactored into distinct scenes. It should be easier to add/remove the input events.

**Comment by calexil** [comment]
Closing as wont fix, unless you wanna take a crack at it

since tha base mappings should work for every controller except custom mods, and those people can just edit the layout.json file
