### ISSUE TITLE
Change menu to mouse right click only

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#14]
Change menu to mouse right click only

**Comment by benmoran56** [comment]
I like this idea. It will be easy to implement. We can put an "OK" button inside the pop-up menu window. 

http://pyglet.readthedocs.io/en/pyglet-1.2-maintenance/api/pyglet/window/pyglet.window.Window.html?highlight=on_mouse_press

We can use the Window class's "on_mouse_press" event to activate the menu.

**Comment by benmoran56** [comment]
Well, it turns out that the simplui module takes controll of the mouse-related event handlers. This makes it tricky to do a right-click menu. Instead, I set it to toggle with the Space button.

**Comment by calexil** [comment]
I just moved its axises
