### ISSUE TITLE
Crop the "select" and "start" images so they're easier to theme

### ISSUE THREAD

**Issue by benmoran56** [calexil/FightstickDisplay#24]
These two are still big transparent PNGs, but maybe they should be smaller so they're easier to theme.

**Comment by calexil** [comment]
feel free to crop and recenter the sprites

**Comment by calexil** [comment]
nvm I did it

https://github.com/calexil/FightstickDisplay/commit/a253ea490f077f2c9c218b40152fc106d35364a1
