### ISSUE TITLE
Different color buttons

### ISSUE THREAD

**Issue by benmoran56** [calexil/FightstickDisplay#25]
We're using the same sprite for all buttons. Would it be nicer looking to have different colors?

**Comment by calexil** [comment]
I like things simple tbh, but if you wanna add color selection feel free.

**Comment by benmoran56** [comment]
I don't really care myself, but I think themers might want to do it. I've got another pull request soon that switches over the the configparser module. As part of that, I've added a section to the layout file so that users can specify another image name:

[layout]
background = [0, 0]
stick = [119, 155]
select = [0, 0]
start = [0, 0]
x = [256, 84]
y = [336, 114]
lt = [507, 110]
rt = [421, 113]
a = [275, 174]
b = [354, 204]
lb = [440, 203]
rb = [527, 200]

[images]
background = background.png
stick = stick.png
select = select.png
start = start.png
x = button.png
y = button.png
lt = button.png
rt = button.png
a = button.png
b = button.png
lb = button.png
rb = button.png
