### ISSUE TITLE
Add recursive gamepad check when gamepad not connected

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#35]
I would like to add a feature to run a loop checking for button inputs to occur that would change the scene from gamepad missing.png to the main scene

**Comment by calexil** [comment]
@benmoran56 point me in the right direction or take a crack yourself

**Comment by benmoran56** [comment]
I was thinking about this...  Right now there is just that if/else check to set the scene. Maybe we can put that in a function, and then call it on a scheduled interval. Something like this: 

```
def set_scene(dt):
    controllers = pyglet.input.get_game_controllers()   
    if len(controllers) > 0:
        controller = controllers[0]
        scene = MainScene(window, controller)
    else:
        scene = TryAgainScene(window)
```
Then we can set an interval to check it:
```
pyglet.clock.schedule_interval(set_scene, 1.0)
```

I think that should work. The question is how often to schedule it for. Maybe once a second is too often...

**Comment by calexil** [comment]
every 3 seconds sounds a little less... strained

**Comment by calexil** [comment]
I'll take a crack at it on stream tonight

**Comment by calexil** [comment]
@benmoran56 you need to re fork, you have conflicts

**Comment by calexil** [comment]
tried you recommendation it does not work.

@benmoran56  live @ https://twitch.tv/calexil in case you wanted to swing by

**Comment by calexil** [comment]
https://github.com/calexil/FightstickDisplay/pull/37


solvedish

**Comment by benmoran56** [comment]
I think we can probably close this, since it's now functional. The new issue is how to prevent the pop up menu from breaking transitions.

**Comment by calexil** [comment]
hmm, @benmoran56 do we even need a deadzone menu?

**Comment by benmoran56** [comment]
I don't think we do.. Maybe it's best to strip all of that menu code out for the time being. We can always revisit it later if we want to.

**Comment by calexil** [comment]
I mean, you weren't getting any false positives right? I'm gonna pull it
