### ISSUE TITLE
Lock the window aspect ratio when scaling/resizing so sprite redraw is clean and full screen is disabled

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#36]
minor improvement for streaming not in a scene: desktop streaming

**Comment by calexil** [comment]
@MegaMissingno you might wanna refork, you are wayyyy behind in commits

**Comment by calexil** [comment]
@benmoran56 any idea how complicated this will be, I might just pull the issue down?

**Comment by benmoran56** [comment]
This won't be complicated at all, but it will require a few dozen lines of OpenGL code. I was planning on working on this soon.

**Comment by benmoran56** [comment]
Initial code is in. It lets you resize to whatever you want, so the image can get skewed. We can leave it like this, or enforce keeping the aspect ratio. We can either do that by putting black bars or pillars into the window (like a movie would do), or by limiting how the window itself can be resized.

**Comment by calexil** [comment]
I'll test it tonight, thanks!

**Comment by calexil** [comment]
hmm doesn't seem to work the images just dissappear, also any reason we pulled vsync=true from the code?

**Comment by calexil** [comment]
reverted until it actually works

**Comment by benmoran56** [comment]
Missed a few OpenGL state setting calls. It worked fine on my Mesa stack Radeon cards, but I guess it's a driver quirk. I made a new pull with everything explicitly called, which should work on everything.

**Comment by calexil** [comment]
still broken, the images and layout do not scale at all, and when the window is scaled smaller that the bg image it dissappears

**Comment by benmoran56** [comment]
Ug, probably best to comment out the entire @window.event  on_draw event at the top for now. We can then try to do it together at some point.  This all works fine on my Mesa stack (Radeon and Nouveau), so it's probably some OpenGL quirk.

**Comment by calexil** [comment]
im on mesa 17.1

**Comment by calexil** [comment]
r9 380x

**Comment by calexil** [comment]
so for this to work the aspect will need to be locked I think

**Comment by calexil** [comment]
gonna try and sort out that wildcard.

not recommended

**Comment by benmoran56** [comment]
Updated the title to reflect the current state of things.

**Comment by calexil** [comment]
I am currently streaming trying to lock the aspect live 

https://www.twitch.tv/calexil

**Comment by calexil** [comment]
@benmoran56 I fixed a buncha image issues, with scaling etc.

rebase when you get a chance

**Comment by calexil** [comment]
self note: reset aspect to decimal, recalculate single dimension, lock down recalculation rates with scheduler

**Comment by calexil** [comment]
@benmoran56 this is essentially solved so I'm about to close it, but one more thing... is there a way to lock the resizing to the correct aspect?

**Comment by calexil** [comment]
we could skip the whole window size reset is the resizing aspect could just be locked

**Comment by benmoran56** [comment]
There doesn't seem to be a platform specifc (Xlib) way to lock the aspect ratio while scaling, so I think we're forced to do it like we were trying to. If we can get it to resize in real-time without recursion issues, that would be idea.

**Comment by calexil** [comment]
I'm callin it solved for now, if you manage to sort our real time resizing, feel free to pr

**Comment by benmoran56** [comment]
Sounds. I'll have a hack at this in some spare time.
