### ISSUE TITLE
Exclude *.pyc files from git

### ISSUE THREAD

**Issue by benmoran56** [calexil/FightstickDisplay#43]
This repository is currently tracking the *.pyc files, which causes headaches when people try to fork and work on the repo. Best practice is to ignore these, so they should be added to a gitignore file:
https://www.atlassian.com/git/tutorials/gitignore

**Comment by calexil** [comment]
please... please communicate with me through something other that github... it's just so slow

irc, telegram, discord, twitch

anything...

**Comment by calexil** [comment]
something is totally broken now
no idea why

**Comment by calexil** [comment]
jd@Marzipan ~/FightstickDisplay $ python fightstick.py 
Traceback (most recent call last):
  File "fightstick.py", line 2, in <module>
    from pyglet.gl import glViewport, glMatrixMode, glOrtho, glLoadIdentity, glScalef
  File "/home/jd/FightstickDisplay/pyglet/gl/__init__.py", line 239, in <module>
    import pyglet.window
  File "/home/jd/FightstickDisplay/pyglet/window/__init__.py", line 1778, in <module>
    from pyglet.window.xlib import XlibWindow as Window
  File "/home/jd/FightstickDisplay/pyglet/window/xlib/__init__.py", line 50, in <module>
    from pyglet.window import key
ImportError: cannot import name key

**Comment by calexil** [comment]
https://github.com/calexil/FightstickDisplay/commit/d108f0f38f7748184a4fd04a5d8676bc699a8828
