### ISSUE TITLE
Implement pyglet.input.gamecontroller.add_mappings_from_file when it is ready in pyglet

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#45]
Add gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt call topyglet/input/gamecontroller.py

as opposed to having the whole array

**Comment by calexil** [comment]
@benmoran56 any help getting started here would be awesome, https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt  will need to be reformatted to the pyglet gamecontroller.py formatting somehow, hopefully on the fly

**Comment by benmoran56** [comment]
Hey JD. Two things - I wrote a tool to automatically parse the SDL controller db from inside of the SDL source tree. You can find that tool here:  https://bitbucket.org/HigashiNoKaze/pyglet/raw/7d02c68f87c8e41faa3b597a0c529c5339a751a1/tools/gen_controller_db.py
The gamecontroller code will make it into pyglet proper after the 2.0 release, which is hopefully not too far out. I may update FightStickDisplay to the gamecontroller branch again in the mean time. 

I also planned to add a function:  `pyglet.input.gamecontroller.add_mappings_from_file` or similar. This would let us add some code to the top of the app that would look for the gamecontrollerdb.txt file in the root of the folder on launch. If it's there, it will add them. This way users can add and update this file by themselves.

**Comment by calexil** [comment]
sick, just let me know so we arent crossing footsteps, I was gonna try and implement a call to the mapping file and parse it like an array so it's formatted correctly, but I guess you did that? ;)

**Comment by calexil** [comment]
@benmoran56 so what I would need to do is something like mash your gen_controller_db.py into the existing gamecontroller.py ? it looks like you were on the way to doing that already(there's commented areas mentioning it)

**Comment by benmoran56** [comment]
Hey, sorry I got distracted and forgot to reply to your other comment.

As you thought, I do already have most of this code written. I will be adding a method to pyglet like `pyglet.gamecontroller.add_mappings_from_file`.

In this program, you will just need to do a few things. First, check if the file exists. If so, call the above method. I think most games look in the base folder. Its probably fine to hard-code to a single file name to start.

**Comment by calexil** [comment]
Now It just needs to download the the db, and the pyglet.gamecontroller.add_mappings_from_file code needs to be completed amirite?

but we also want it to append not overwrite, in case we have user submitted mappings that that db doesnt have

**Comment by benmoran56** [comment]
Do you think it's wise to auto-download at all?
If we want the extra mappings included, maybe just ship the db file. That way users can just replace it.

**Comment by calexil** [comment]
hmm, good point

but it does get updated often, and its peer reviewed

**Comment by calexil** [comment]
@benmoran56 any news on the merge?

**Comment by benmoran56** [comment]
Hey!  Sorry, I wasn't sure from your last comment that you wanted to go ahead with it.   Do we know if github raw links are stable?

**Comment by calexil** [comment]
I mean, I dont see the db going anywhere in the near future, steamos uses it.

**Comment by benmoran56** [comment]
I've been really busy these days, but it should be a simple addition. This code *should* work to download the db, and save it in the current directory: 
```
import urllib.request

url = "https://raw.githubusercontent.com/gabomdq/SDL_GameControllerDB/master/gamecontrollerdb.txt"


with urllib.request.urlopen(url) as response, open("gamecontrollerdb.txt", 'wb') as f:
    f.write(response.read())
```

It just needs to be added in before the other code that tries loading the file. 

I guess at some point, we could make it a launch option? I'm not sure how it will behave if there is a bad connection, so the download part might be better wrapped in a try/except block. 
If you want to try adding this in, I can have a look later to make sure it looks good. Otherwise, I can put together a proper pull request in the near future.

**Comment by calexil** [comment]
jd@jd-work ~/FightstickDisplay $ python fightstick.py 
Traceback (most recent call last):
  File "fightstick.py", line 19, in <module>
    with urllib.request.urlopen(url) as response, open("gamecontrollerdb.txt", 'wb') as f:
AttributeError: addinfourl instance has no attribute '__exit__'

**Comment by benmoran56** [comment]
Let me guess, Python 2? I don't think urlopen can be used as a context manager there.

**Comment by calexil** [comment]
yeah I think its all mostly 2.7 , although I have 3 installed

**Comment by benmoran56** [comment]
This should work on both Python 2 and 3, with all the extra mess that entails. I personally wouldn't bother with Python 2 support anymore. It's pretty much dead at this point except for legacy code bases. 

```
try:
    # Legacy Python (remove in 2020)
    from urllib2 import urlopen
    from urllib2 import HTTPError
except ImportError:
    from urllib.request import urlopen
    from urllib.error import HTTPError

url = "https://raw.githubusercontent.com/gabomdq/SDL_GameControllerDB/master/gamecontrollerdb.txttt"

try:
    response = urlopen(url)
    with open("gamecontrollerdb.txt", 'wb') as f:
        f.write(response.read())
except HTTPError:
    print("Unable to download GameController database from:\n -> {0}".format(url))
```

**Comment by calexil** [comment]
I guess my real question now is: does pyglet.input.gamecontroller.add_mappings_from_file actually work?

**Comment by calexil** [comment]
also @benmoran56 I just dropped 2.7 support, you are right... its going to die soon anyways

**Comment by benmoran56** [comment]
pyglet just loads in a text file, and reads each line. 

Grabbing that DB from the URL is a separate process which just saves the file to disk. 
I'm not sure what Codefactor is complaining about.

**Comment by calexil** [comment]
@benmoran56 is pyglet.input.gamecontroller.add_mappings_from_file completed and ready to use?

if so I guess some lines and files need to be changed

**Comment by calexil** [comment]
nvm I think it's actually working lol

**Comment by benmoran56** [comment]
OK cool. Sorry I kinda got busy with other stuff. I do now have some time to work on this if there are still issues.
