### ISSUE TITLE
Fix 'Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.' issue in fightstick.py

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#48]
[CodeFactor](https://www.codefactor.io/repository/github/calexil/fightstickdisplay/overview/master) found an issue: Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.

It's currently on:
[fightstick.py:19
](https://www.codefactor.io/repository/github/calexil/fightstickdisplay/source/master/fightstick.py#L19)Commit 68bb7f86e4aa96ef140f624e6fe3494a8a39af0f

**Comment by calexil** [comment]
@benmoran56 not sure if this is even an issue, I think its mad that the file is imported to "f"

**Comment by benmoran56** [comment]
https://stackoverflow.com/questions/48779202/audit-url-open-for-permitted-schemes-allowing-use-of-file-or-custom-schemes#48780869

Looks like we can wrap the url string in a Request object, and it might quiet it up.

**Comment by calexil** [comment]
hmm I tried both options presented, but neither seemed to work. 

the first threw the same error, and the second got stuck at the 'else' part of the code

**Comment by calexil** [comment]
this is a non issue due to the nature of the url being dl'd closed

ssl got our back here
