### ISSUE TITLE
Add a popup menu for deadzone config

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#51]
Add a popup menu for deadzone config and color selection

for reference: https://github.com/calexil/FightstickDisplay/commit/ddcb35e42429dd59b108f597b45cda4f413f65c2

**Comment by calexil** [comment]
I would like to add this back in so people with sloppy pads can get them centered correctly.

Also how trivial would a color selection dialog be?

**Comment by benmoran56** [comment]
What do you mean about color selection? The button colors? We're using images for them now, but we _could_ just make them out of shapes. 
```py
pyglet.shape.Circle(....)
```
If we do it that way, we can set any color we like.

**Comment by calexil** [comment]
hmm, well I haven't had any requests for this feature and that sounds like a bunch more work. I think I'm gonna backburner this one until I get the HB button mappings correctly aligned

**Comment by benmoran56** [comment]
For the deadzone config,  it would be easy to do as a separate "Scene".
We could make it so that if you press some hotkey, it will change to the config screen with a few slider widgets.

**Comment by calexil** [comment]
if it's trivial to ad it back in feel free to PR, I am working on lining up the buttons for HB, and redo-ing the entire dpad section

**Comment by calexil** [comment]
okay ben I finally got the hitbox version working and pushed rc 2.0

this is next up, so let me know your thoughts on how to proceed

**Comment by benmoran56** [comment]
Check out the `config_scene` branch. 
You can enter the deadzone configuration scene by pressing the "Guide" button. 
It's incomplete, but should be functional.

**Comment by calexil** [comment]
did any of my laboring help out? lol

**Comment by calexil** [comment]
https://github.com/calexil/FightstickDisplay/commit/870c39489265931dcb74acc262dc05a7899dd934

**Comment by calexil** [comment]
lol, looks like no. I tried.

**Comment by benmoran56** [comment]
Ha, that's alright. I did just add your background image :smile: 

The project is now complex enough that it really needed a bit of abstraction, so I made more well-defined classes for everything.

It's using the "guide" button to switch to the config menu, but we probably also want to add a hook for some Keyboard key as well since not all devices have a guide button.

**Comment by calexil** [comment]
b82bf22
