### ISSUE TITLE
fix black line on buttons when window is scaled

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#53]
fix black line on buttons when window is scaled
![Screenshot at 2021-01-15 19-05-53](https://user-images.githubusercontent.com/3487071/104790163-c649bf00-5764-11eb-9469-06ab53decc98.png)

**Comment by benmoran56** [comment]
This should be fixed in the `pyglet_next` branch.  These are OpenGL texture artifacts, but the newer pyglet releases now add a 1-pixel transparent border by default.

**Comment by calexil** [comment]
#62
