### ISSUE TITLE
X Y RB LB naming scheme completely flipped in hb/base

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#57]
X Y RB LB completely flipped, addressing inside code main code not changing result, possible gamecontrollerdb issue

**Comment by calexil** [comment]
x y rb lb = lb rb y x

**Comment by benmoran56** [comment]
Oh yeah, the db format changed.. I'll see if I can make an update to this soon.

**Comment by calexil** [comment]
yeah I've been doing a ton of work trying to support Hitboxes

gonna be tricky since I don't own one

**Comment by calexil** [comment]
#62
