### ISSUE TITLE
no directional register for hitbox version

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#59]
hats =  not working while testing from xb360 controller, no hb to actually test

**Comment by calexil** [comment]
If anyone reading this want's to loan me a hitbox, I would greatly appreciate it. I'll cover the shipping

**Comment by benmoran56** [comment]
I just pushed a new branch:  `pyglet_next`. This contains the latest pyglet dev release, which has a ton of fixes in it. 
If you wouldn't mind giving that a try, we can reevaluate these open issues. 

One thing that does **not** currently work, is image scaling. The image stays the same size when you scale the window.

**Comment by calexil** [comment]
well we cant have scaling broken, any timeline on a fix for that?

**Comment by calexil** [comment]
I can work with your branch to get all the names right, and the layout fixed, but not until I am sure scaling will be fixed relatively soon

**Comment by benmoran56** [comment]
The window scaling should be working now. Can you give it a try and see how many of the other issues remain with this branch?

**Comment by calexil** [comment]
@benmoran56 crushed a ton of bugs, excellent work over there at the pig labs ;P

**Comment by calexil** [comment]
Okay I have confirmed that the hitbox registers directionals as hats, just like a dpad

so not I just need to hook the naming together and let the button pressed section do the rest

https://github.com/calexil/FightstickDisplay/blob/49b07bdb8b808f1f14256a2586b74b2f5a883901/fightstick_hb.py#L188

this line is what I think I need to work with, but it may be just as simple as what I already did by adding the sprites

**Comment by benmoran56** [comment]
If the directional buttons are just hats, then it _should_ work fine as it is?

**Comment by calexil** [comment]
well no because the hitbox directional buttons are scattered about and different sizes, they will need to have x,y coordinates
and the dpad presses needs to cause the sprites to appear in those locations

**Comment by calexil** [comment]
@benmoran56 https://github.com/calexil/FightstickDisplay/commit/f81a0119b8213fbf2a47b7c08f02ab02b93868d9

I am so close, I just need the dpad presses to cause the sprites to draw, not sure how

**Comment by calexil** [comment]
https://github.com/calexil/FightstickDisplay/blob/4b5a361068e1feda1a0cee9f5c06f7e68d896e9c/fightstick_hb.py#L180

here's my best guess, I tried reading the pyglet docs on sprites, but couldn't find tha answer as to how to have a dpad event be considered a button press

**Comment by benmoran56** [comment]
If I understand it correctly, the directional inputs on this controller emmit button events?

**Comment by calexil** [comment]
yeah, hats

**Comment by calexil** [comment]
basically pyglet needs to treat the dpad events as button presses, not sure how to trick it into doing that though

**Comment by calexil** [comment]
wait a minute, hats are joystick events, so we just need to check for the extremes and have them trigger the sprites

also it should with with dpad, since the output changes from hitbox version to version

**Comment by calexil** [comment]
https://github.com/calexil/FightstickDisplay/commit/b3fb6133e4a725c7d841eea3a58b17d3118322ea
