### ISSUE TITLE
layout inversion and pixel shift in hitbox version

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#60]
shift seems to be by -35, -20 approximately. after a vertical flip transform

**Comment by benmoran56** [comment]
Does this controller work with the new code out of the box now? There seems to be mappings for it.

**Comment by calexil** [comment]
unfortunately I dont own a hitbox to test, so im taking a shot in the dark on this upgrade

**Comment by calexil** [comment]
https://github.com/calexil/FightstickDisplay/commit/173c8f70c516c0993efdf438d005d5f2065f1038

figured out how to fix this, fixing tonight

**Comment by calexil** [comment]
https://github.com/calexil/FightstickDisplay/commit/f81a0119b8213fbf2a47b7c08f02ab02b93868d9

fixed , now to just get the directionals to cause the direction sprites to draw
