### ISSUE TITLE
Button mapping nomenclature appears to be incorrect

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#61]
https://github.com/calexil/FightstickDisplay/blob/2e2bdac498909bc5b0a6eb9c29e39100b15df69f/fightstick.py#L152

https://github.com/calexil/FightstickDisplay/blob/2e2bdac498909bc5b0a6eb9c29e39100b15df69f/fightstick.py#L199

**Comment by benmoran56** [comment]
This can be changed, and then adjusted in the configuration.

**Comment by benmoran56** [comment]
We should make sure the names match up internally to fightstick.py, and just update the layout.ini to adjust things.

**Comment by calexil** [comment]
#62
