### ISSUE TITLE
Add Windows build

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#63]
Trying to figure out how to do this with py2exe no luck so far, but its on the timeline for  version 2.0 release

**Comment by benmoran56** [comment]
I don't know about py2exe, but PyInstaller works pretty well.

**Comment by calexil** [comment]
not familiar with it, tried it and it seemed to do something made a folder called dist full of stuff, but no executable

**Comment by calexil** [comment]
backburnered for release 2.0
