### ISSUE TITLE
fightstick display crashes when more than one controller is plugged in

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#66]
jd@Marzipan:~/FightstickDisplay$ python3 fightstick.py
Added additional controller mappings from 'gamecontrollerdb.txt'
Traceback (most recent call last):
  File "fightstick.py", line 237, in <module>
    set_scene()
  File "fightstick.py", line 228, in set_scene
    scene = MainScene(window, controller)
  File "fightstick.py", line 126, in __init__
    self.fightstick.open()
  File "/home/jd/FightstickDisplay/pyglet/input/evdev.py", line 398, in open
    self._rumble_strong = self.device.ff_create_effect(0, 0, 0)
  File "/home/jd/FightstickDisplay/pyglet/input/evdev.py", line 352, in ff_create_effect
    fcntl.ioctl(self._fileno, 0x40304580, view, True)
OSError: [Errno 28] No space left on device

**Comment by benmoran56** [comment]
That looks like a pyglet bug. I'll have a look at that soon.

**Comment by benmoran56** [comment]
Try the `config_scene` branch. The pyglet release was updated along with other stuff.

**Comment by calexil** [comment]
still present, once this is fixed I can merge the branches and get to the nasty business of making the hitbox version work again.

I tried last week and it was all kinds of broken

**Comment by calexil** [comment]
@benmoran56 hey bud, having an issue.

the program has suddenly started loading EXTREMELY slowly

I have narrowed the issue down to lines 23-34, the urllib.request.urlopen(url) function that pulls in the sdl controller data. When I comment those out it loads instantly, as expected.

Any insight as to why it would suddenly be hanging like this?

**Comment by calexil** [comment]
I have tried adding headers to get around any kind of filtering or bot prevention https://raw.githubusercontent.com may have implemented, but to no avail

**Comment by calexil** [comment]
https://github.com/calexil/FightstickDisplay/commit/c334753d3707aa9c3e38e8d996ddea509dc9f7b3

**Comment by benmoran56** [comment]
Lets update to the latest pyglet release. 
There were lots of Controller related updates in the last year. 

Also, if no specific mapping is detected for a Controller,
pyglet now automatically one by using the [Linux gamepad specification](https://www.kernel.org/doc/html/latest/input/gamepad.html#linux-gamepad-specification).  
Because of that, it's not as important to pull those latest mapping files. That whole section can be removed. What do you think?

**Comment by calexil** [comment]
Sounds good;

I tried dropping in the files for the latest release but it caused crashes, so feel free to issue a PR for me to review.

I am unsure of the correct method of updating pyglet.

**Comment by calexil** [comment]
oh and make sure you use the master branch

**Comment by benmoran56** [comment]
Cool, I'll make a PR either tonight or tomorrow.
There is also a new `ControllerManager` class in pyglet, so hot plugging controllers is much simpler. I'll redo the set_scene function as well.

**Comment by calexil** [comment]
doing some comment cleanup rn, so make sure to get a clean clone if you're gonna do it friday

**Comment by calexil** [comment]
if you haven't already, hold off on this. the program has suddenly started working again inexplicably.  I guess they lifted the lockdown they put in place, who knows. If you still wanna update pyglet and make changes wait till I give the word I'm done reverting things

**Comment by benmoran56** [comment]
OK no problem. Just let me know when you're done, and I'll rebase off of that.

**Comment by calexil** [comment]
ok I am done. go for it

**Comment by benmoran56** [comment]
Just to restate, I think It's a good idea to remove the automatic downloading of the controller db.
It's not really necessary anymore, and it can be updated in the repo manually from time to time.
With the new pyglet release, Controllers will always be detected now, and new devices should have correct mapping automatically (if the drivers follow the Linux kernel spec).

**Comment by calexil** [comment]
okay

**Comment by benmoran56** [comment]
I pushed my current work to this branch (only the main fightstick.py for now):
https://github.com/calexil/FightstickDisplay/tree/pyglet_205

I made a new SceneManager class, which uses the new ControllerManager class. This should handle hot-plugging without having to poll.

**Comment by calexil** [comment]
so everything is working amazing now, went from 98% cpu use at idle to ~8%, but one caveat`, we are still loading controller mappings from gamecontrollerdb.txt correct? So if that file never gets updated and new controllers get added to the market and mapped at the sdl2 source: https://github.com/gabomdq/SDL_GameControllerDB, how does the program get that data with the urllib.request.urlopen(url) removed? This seems like it will create issues in the future where peoples new fightsticks wont work and we will have to manually update the program to include them, instead of the automatic manner in which they were managed before.

**Comment by benmoran56** [comment]
Wow, 98%? Not sure how that happened.  :sweat_drops:  8% sounds more like it.

It's not strictly necessary to have a mapping for every controller now, because the latest pyglet is auto-mapping them via the Linux Gamepad Specification. Even if there is no mapping it will still work, but the user might need to change the layout. (Actually, all new evdev drivers are supposed to adhere to the Linux Gamepad Specs, so they _should_ be mapped correctly). 

For that reason, it's not as critical to keep that mapping DB updated. I think it would be enough to just manually update it in the repository once it a while, for good measure.

**Comment by calexil** [comment]
understood, merging

**Comment by calexil** [comment]
resolved by

https://github.com/calexil/FightstickDisplay/commit/901cc8564c84c87cd2080b52f7ef3e6f4d487b2f
