### ISSUE TITLE
config_scene branch crashes when launched from a .desktop launcher and the guide button is pressed a second time(to close it)

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#69]
no error thrown

**Comment by benmoran56** [comment]
I know what's going on. When you exit the config screen, it saves the updated deadzone info in the theme/layout.ini file. 
When launching from the .desktop launcher, it can't find it. 
I'll make a quick fix.

**Comment by benmoran56** [comment]
This should have fixed it: 
https://github.com/calexil/FightstickDisplay/commit/4a60e75495989454d6f7a13249990f9df8c8281f

**Comment by calexil** [comment]
4a60e75
