### ISSUE TITLE
config_scene: App crashes when a controller is not plugged in, trace below

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#73]
python3 '/home/jd/FightstickDisplay-config_scene/fightstick.py' -d
No controllers found
introduced by this commit:

https://github.com/calexil/FightstickDisplay/commit/6e211b63b2e59004e1f91fe79ab400a53bca68af

**Comment by calexil** [comment]
this is happening now because the app is no longer checking constantly for a controller as it did previously

**Comment by benmoran56** [comment]
This is now fixed in the config_scene branch.
