### ISSUE TITLE
Add a deadzone menu.

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#75]

**Comment by benmoran56** [comment]
So we're using PNGs for the buttons now, but should they just be changed to use a Circle shape? `pyglet.shapes.Circle(...)`
Using a shape would be better, because we can set any color we want, but it will just be limited to flat shapes. 
With the images, users _could_ do any kind of custom images they want, but I guess noone is really doing that?

**Comment by calexil** [comment]
I'll worry about this one, I have something cool in mind I'll explain later

**Comment by calexil** [comment]
https://github.com/calexil/FightstickDisplay/blob/master/DeadzoneScene.py

**Comment by calexil** [comment]
@benmoran56 tried merging the new classes and handlers you made in config_scene_branch, to little success lots of graphical issues after all the debugging. hopefully you can figure out how to merge a deadzone menu into whats in master both fightstick.py and fightstick_hb.py, because I just spend like 2 hours trying and failing

**Comment by benmoran56** [comment]
I can do this, but might need a few days. Just been busy.

**Comment by calexil** [comment]
no rush, everything's working fine now anyways. I also added back in the database download, despite it probably not being needed, better safe than sorry. I prefer a bit of hands-off future-proofing to having slightly cleaner code.

**Comment by calexil** [comment]
ugh @benmoran56 I have been trying for 3 hours to merge your changes in config_scene_branch, into the main master, to no avail.

I am trying to avoid doing a full rewrite with you scenemanager class, but I can't seem to pull it off, any help would be greatly appreciated.

I kinda wanna just have the deadzone scene come up and down on the guide button press, but I can't quite reconcile that idea with the current draw stack.

**Comment by calexil** [comment]
@benmoran56  made another attempt, to no avail.

the main issue I am running into is using your baseclass, scenemanager, or trying to do it as an independent class that is button triggered.

check my latest commit, I am a bit lost

also you need to get on the reddit pyglet mod team, as a reminder

**Comment by calexil** [comment]
https://github.com/calexil/FightstickDisplay/commit/10b194faeef82a2c8d3322c350fa1001169a7f35

still need help ben, I cant wrap my mind around your scene.manager class for the life of me

**Comment by benmoran56** [comment]
Doh!  Sorry for leaving this hanging. I actually wrote most of the code already, but I think it's in conflict with master now.
The code I wrote is using either "guide" or the "F1" key to enter the config scene.

**Comment by benmoran56** [comment]
Check out the `config_scene` branch. You can use either F1 or the Guide button to enter the scene. 
Exit the scene by pressing the Guide button again, or _any_ key on the keyboard.

**Comment by calexil** [comment]
https://github.com/calexil/FightstickDisplay/commit/3c1c12b55d53b93e35ddc056c2331bd17a9387b7
