### ISSUE TITLE
Lets consolidate the launcher scripts

### ISSUE THREAD

**Issue by benmoran56** [calexil/FightstickDisplay#9]
Currently there are seperate scripts for x360 and ps4, as well as an experimental universal one.
(Only the experimental universal script supports theme layout changes at the moment). 

We should configure the buttons layout in fightstick.py. After that, it should work universally on all sticks, and avoid the need for two seperate launchers.

**Comment by calexil** [comment]
agreed, if you know what parts of the 360py to pull out so my q1 still works with a single main launcher. pull and pr

**Comment by calexil** [comment]
it looks like you started this in the main launcher, Ill test it tonight.

I think the mappings may still be wrong though

**Comment by benmoran56** [comment]
Thanks, it's hard for me to do the final configuration since I don't have a 360/ps4 compatible stick at the moment. I'm sure the mappings are wrong, but all of the code should be there to configure it correctly. The stick buttons that are actual "buttons" should be easy. The question is if the other buttons are x360 triggers, or right stick, shoulder buttons, etc. If you have trouble, I can make a little script that spits out the button names/types when you press them.

**Comment by calexil** [comment]
hmm all buttons are being detected, they are just incorrect, what to I change to edit the config

**Comment by calexil** [comment]
Fixed, and fixed. 

We are now in beta boise!!!!

**Comment by calexil** [comment]
@benmoran56 I got the mapping sorted out by editing the layout.json

It now defaults to being the correct mapping for xb360 controllers

this solution is less than optimal so at somepoint we will need to make a configuration diaglogue

something like.... flash the desired button until the user hits it on their stick... then match the pressed button  to the appropriate image in the layout.json

this should only run once, so we'll need to sort that out

**Comment by benmoran56** [comment]
That's one way to do it!  Also, thanks for the project invite.
If it's OK with you, I'll make a new branch for testing some GUI libraries for making dialogues.

**Comment by calexil** [comment]
go for it
